/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PointsRouteImport } from './routes/points'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BottleExchangeRouteImport } from './routes/bottle-exchange'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RiderRouteRouteImport } from './routes/rider/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIndexRouteImport } from './routes/rider/index'
import { Route as RiderProfileRouteImport } from './routes/rider/profile'
import { Route as RiderLoginRouteImport } from './routes/rider.login'
import { Route as RiderEarningsRouteImport } from './routes/rider/earnings'
import { Route as RiderDashboardRouteImport } from './routes/rider/dashboard'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BottleExchangeRoute = BottleExchangeRouteImport.update({
  id: '/bottle-exchange',
  path: '/bottle-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRouteRoute = RiderRouteRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRouteRoute,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RiderRouteRoute,
} as any)
const RiderLoginRoute = RiderLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RiderRouteRoute,
} as any)
const RiderEarningsRoute = RiderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => RiderRouteRoute,
} as any)
const RiderDashboardRoute = RiderDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RiderRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rider': typeof RiderRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bottle-exchange': typeof BottleExchangeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bottle-exchange': typeof BottleExchangeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider': typeof RiderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rider': typeof RiderRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bottle-exchange': typeof BottleExchangeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rider'
    | '/auth'
    | '/bottle-exchange'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/points'
    | '/profile'
    | '/rider/dashboard'
    | '/rider/earnings'
    | '/rider/login'
    | '/rider/profile'
    | '/rider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bottle-exchange'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/points'
    | '/profile'
    | '/rider/dashboard'
    | '/rider/earnings'
    | '/rider/login'
    | '/rider/profile'
    | '/rider'
  id:
    | '__root__'
    | '/'
    | '/rider'
    | '/auth'
    | '/bottle-exchange'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/points'
    | '/profile'
    | '/rider/dashboard'
    | '/rider/earnings'
    | '/rider/login'
    | '/rider/profile'
    | '/rider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RiderRouteRoute: typeof RiderRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BottleExchangeRoute: typeof BottleExchangeRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRoute
  PointsRoute: typeof PointsRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bottle-exchange': {
      id: '/bottle-exchange'
      path: '/bottle-exchange'
      fullPath: '/bottle-exchange'
      preLoaderRoute: typeof BottleExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/rider/login': {
      id: '/rider/login'
      path: '/login'
      fullPath: '/rider/login'
      preLoaderRoute: typeof RiderLoginRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/rider/earnings': {
      id: '/rider/earnings'
      path: '/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof RiderEarningsRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/rider/dashboard': {
      id: '/rider/dashboard'
      path: '/dashboard'
      fullPath: '/rider/dashboard'
      preLoaderRoute: typeof RiderDashboardRouteImport
      parentRoute: typeof RiderRouteRoute
    }
  }
}

interface RiderRouteRouteChildren {
  RiderDashboardRoute: typeof RiderDashboardRoute
  RiderEarningsRoute: typeof RiderEarningsRoute
  RiderLoginRoute: typeof RiderLoginRoute
  RiderProfileRoute: typeof RiderProfileRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteRouteChildren: RiderRouteRouteChildren = {
  RiderDashboardRoute: RiderDashboardRoute,
  RiderEarningsRoute: RiderEarningsRoute,
  RiderLoginRoute: RiderLoginRoute,
  RiderProfileRoute: RiderProfileRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteRouteWithChildren = RiderRouteRoute._addFileChildren(
  RiderRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RiderRouteRoute: RiderRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BottleExchangeRoute: BottleExchangeRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRoute,
  PointsRoute: PointsRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
