/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PointsRouteImport } from './routes/points'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as RiderRouteRouteImport } from './routes/rider/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIndexRouteImport } from './routes/rider/index'
import { Route as ConsumerIndexRouteImport } from './routes/consumer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RiderProfileRouteImport } from './routes/rider/profile'
import { Route as RiderLoginRouteImport } from './routes/rider/login'
import { Route as RiderEarningsRouteImport } from './routes/rider/earnings'
import { Route as RiderDashboardRouteImport } from './routes/rider/dashboard'
import { Route as ConsumerLoginRouteImport } from './routes/consumer/login'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRidersRouteImport } from './routes/admin/riders'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConsumersRouteImport } from './routes/admin/consumers'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRouteRoute = RiderRouteRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRouteRoute,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RiderRouteRoute,
} as any)
const RiderLoginRoute = RiderLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RiderRouteRoute,
} as any)
const RiderEarningsRoute = RiderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => RiderRouteRoute,
} as any)
const RiderDashboardRoute = RiderDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RiderRouteRoute,
} as any)
const ConsumerLoginRoute = ConsumerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConsumerRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConsumersRoute = AdminConsumersRouteImport.update({
  id: '/consumers',
  path: '/consumers',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/rider': typeof RiderRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consumer': typeof ConsumerRouteWithChildren
  '/landing': typeof LandingRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/consumers': typeof AdminConsumersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/consumer/login': typeof ConsumerLoginRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/landing': typeof LandingRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/consumers': typeof AdminConsumersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/consumer/login': typeof ConsumerLoginRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin': typeof AdminIndexRoute
  '/consumer': typeof ConsumerIndexRoute
  '/rider': typeof RiderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/rider': typeof RiderRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consumer': typeof ConsumerRouteWithChildren
  '/landing': typeof LandingRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/consumers': typeof AdminConsumersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/consumer/login': typeof ConsumerLoginRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/rider'
    | '/cart'
    | '/checkout'
    | '/consumer'
    | '/landing'
    | '/orders'
    | '/points'
    | '/profile'
    | '/settings'
    | '/support'
    | '/terms'
    | '/admin/consumers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/consumer/login'
    | '/rider/dashboard'
    | '/rider/earnings'
    | '/rider/login'
    | '/rider/profile'
    | '/admin/'
    | '/consumer/'
    | '/rider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/landing'
    | '/orders'
    | '/points'
    | '/profile'
    | '/settings'
    | '/support'
    | '/terms'
    | '/admin/consumers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/consumer/login'
    | '/rider/dashboard'
    | '/rider/earnings'
    | '/rider/login'
    | '/rider/profile'
    | '/admin'
    | '/consumer'
    | '/rider'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/rider'
    | '/cart'
    | '/checkout'
    | '/consumer'
    | '/landing'
    | '/orders'
    | '/points'
    | '/profile'
    | '/settings'
    | '/support'
    | '/terms'
    | '/admin/consumers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/consumer/login'
    | '/rider/dashboard'
    | '/rider/earnings'
    | '/rider/login'
    | '/rider/profile'
    | '/admin/'
    | '/consumer/'
    | '/rider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  RiderRouteRoute: typeof RiderRouteRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ConsumerRoute: typeof ConsumerRouteWithChildren
  LandingRoute: typeof LandingRoute
  OrdersRoute: typeof OrdersRoute
  PointsRoute: typeof PointsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/consumer/': {
      id: '/consumer/'
      path: '/'
      fullPath: '/consumer/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/rider/login': {
      id: '/rider/login'
      path: '/login'
      fullPath: '/rider/login'
      preLoaderRoute: typeof RiderLoginRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/rider/earnings': {
      id: '/rider/earnings'
      path: '/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof RiderEarningsRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/rider/dashboard': {
      id: '/rider/dashboard'
      path: '/dashboard'
      fullPath: '/rider/dashboard'
      preLoaderRoute: typeof RiderDashboardRouteImport
      parentRoute: typeof RiderRouteRoute
    }
    '/consumer/login': {
      id: '/consumer/login'
      path: '/login'
      fullPath: '/consumer/login'
      preLoaderRoute: typeof ConsumerLoginRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/consumers': {
      id: '/admin/consumers'
      path: '/consumers'
      fullPath: '/admin/consumers'
      preLoaderRoute: typeof AdminConsumersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminConsumersRoute: typeof AdminConsumersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminConsumersRoute: AdminConsumersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface RiderRouteRouteChildren {
  RiderDashboardRoute: typeof RiderDashboardRoute
  RiderEarningsRoute: typeof RiderEarningsRoute
  RiderLoginRoute: typeof RiderLoginRoute
  RiderProfileRoute: typeof RiderProfileRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteRouteChildren: RiderRouteRouteChildren = {
  RiderDashboardRoute: RiderDashboardRoute,
  RiderEarningsRoute: RiderEarningsRoute,
  RiderLoginRoute: RiderLoginRoute,
  RiderProfileRoute: RiderProfileRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteRouteWithChildren = RiderRouteRoute._addFileChildren(
  RiderRouteRouteChildren,
)

interface ConsumerRouteChildren {
  ConsumerLoginRoute: typeof ConsumerLoginRoute
  ConsumerIndexRoute: typeof ConsumerIndexRoute
}

const ConsumerRouteChildren: ConsumerRouteChildren = {
  ConsumerLoginRoute: ConsumerLoginRoute,
  ConsumerIndexRoute: ConsumerIndexRoute,
}

const ConsumerRouteWithChildren = ConsumerRoute._addFileChildren(
  ConsumerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  RiderRouteRoute: RiderRouteRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ConsumerRoute: ConsumerRouteWithChildren,
  LandingRoute: LandingRoute,
  OrdersRoute: OrdersRoute,
  PointsRoute: PointsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
